trigger:
- main

pool:
  name: Default          # Pool donde está el agente autohospedado
  demands:
    - Agent.Name -equals ip-172-31-8-73  # Nombre del agente

variables:
  buildConfiguration: 'Release'
  deployPath: '/var/www/contratos'        # Ruta en el servidor AWS
  serverIP: '172.31.8.73'                 # IP del servidor
  sshUser: 'ec2-user'                     # Usuario SSH
  sshKey: '$(SSH_PRIVATE_KEY)'            # Clave SSH desde variables secretas

stages:
- stage: Build
  displayName: 'Build .NET Core API'
  jobs:
  - job: Build
    displayName: 'Compile and Publish'
    steps:
    - checkout: self
      displayName: 'Checkout Code'

    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Core Project'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload Build Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy to AWS Linux Server'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Copy Files and Restart Service'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: Bash@3
      displayName: 'Copy Files and Restart Service'
      inputs:
        targetType: 'inline'
        script: |
          echo "Starting deployment..."

          # Crear clave privada temporal
          echo "Creando clave privada temporal..."
          echo "$(sshKey)" > private_key.pem
          chmod 600 private_key.pem

          # Crear carpeta destino si no existe
          echo "Creando carpeta de destino..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) "sudo mkdir -p $(deployPath) && sudo chown ec2-user:ec2-user $(deployPath)"

          # Copiar archivo ZIP al servidor
          echo "Copiando archivos al servidor AWS..."
          scp -o StrictHostKeyChecking=no -i private_key.pem $(System.ArtifactsDirectory)/drop/*.zip $(sshUser)@$(serverIP):$(deployPath)

          # Extraer archivos y reiniciar servicio
          echo "Extrayendo archivos y reiniciando servicio..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) << 'EOF'
          unzip -o $(deployPath)/*.zip -d $(deployPath)
          sudo systemctl daemon-reload
          sudo systemctl restart contratos.service
          EOF

          # Limpiar clave privada temporal
          rm -f private_key.pem
          echo "Despliegue completado correctamente."
