trigger:
- main

pool:
  name: Default  # Usa el pool de agentes autohospedados
  demands:
    - Agent.Name -equals AWS-Linux-Agent  # Nombre de tu agente autohospedado

variables:
  buildConfiguration: 'Release'
  deployPath: '/var/www/contratos'        # Ruta de destino en el servidor
  serverIP: '172.31.8.73'                 # IP del servidor Linux en AWS
  sshUser: 'ec2-user'                     # Usuario del servidor Amazon Linux
  sshKey: '$(SSH_PRIVATE_KEY)'            # Clave SSH secreta

stages:
- stage: Build
  displayName: 'Build .NET Core API'
  jobs:
  - job: Build
    displayName: 'Compile and Publish'
    steps:
    - checkout: self   # Realizar checkout del repositorio

    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Core Project'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload Build Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to AWS Linux Server'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Copy and Deploy to AWS'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: Bash@3
      displayName: 'Copy Files and Restart Service'
      inputs:
        targetType: 'inline'
        script: |
          echo "Starting deployment..."

          # Validar si los archivos existen
          if [ ! -d "$(System.ArtifactsDirectory)/drop" ]; then
            echo "Error: No se encontraron los archivos a desplegar."
            exit 1
          fi

          # Crear la clave privada temporal
          echo "Creando clave privada temporal..."
          echo "$(sshKey)" > private_key.pem
          chmod 600 private_key.pem

          # Crear carpeta de destino en el servidor si no existe
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) "mkdir -p $(deployPath)"

          # Copiar archivos al servidor
          echo "Copiando archivos al servidor..."
          scp -o StrictHostKeyChecking=no -i private_key.pem -r $(System.ArtifactsDirectory)/drop/* $(sshUser)@$(serverIP):$(deployPath)

          # Reiniciar el servicio en el servidor
          echo "Reiniciando servicio en el servidor..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) << 'EOF'
          sudo systemctl daemon-reload
          sudo systemctl restart contratos.service
          EOF

          # Eliminar la clave privada temporal
          rm -f private_key.pem
          echo "Despliegue completado correctamente."
