trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Pipeline ejecutado en un agente Ubuntu de Azure

variables:
  buildConfiguration: 'Release'
  deployPath: '/var/www/contratos'      # Ruta de despliegue en el servidor AWS
  serverIP: '172.31.8.73'               # IP del servidor Amazon Linux
  sshUser: 'ec2-user'                   # Usuario de Amazon Linux
  sshKey: '$(SSH_PRIVATE_KEY)'          # Clave privada SSH (variable secreta)

stages:
- stage: Build
  displayName: 'Build .NET Core API'
  jobs:
  - job: Build
    displayName: 'Compile and Publish'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Core Project'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload Build Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy to AWS Linux Server'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Copy and Deploy to AWS'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: Bash@3
      displayName: 'Copy Files and Restart Service'
      inputs:
        targetType: 'inline'
        script: |
          echo "Starting deployment..."

          # Verificar si los archivos existen
          if [ ! -d "$(System.ArtifactsDirectory)/drop" ]; then
            echo "Error: No se encontraron los archivos a desplegar."
            exit 1
          fi

          # Crear clave privada temporal
          echo "Creando clave privada temporal..."
          echo "$(sshKey)" > private_key.pem
          chmod 600 private_key.pem

          # Copiar archivos al servidor
          echo "Copiando archivos al servidor..."
          scp -o StrictHostKeyChecking=no -i private_key.pem -r $(System.ArtifactsDirectory)/drop/* $(sshUser)@$(serverIP):$(deployPath)

          # Reiniciar el servicio en el servidor
          echo "Reiniciando servicio en el servidor..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) << 'EOF'
          sudo systemctl daemon-reload
          sudo systemctl restart contratos.service
          echo "Servicio reiniciado correctamente."
          EOF

          # Eliminar clave privada temporal
          rm -f private_key.pem
          echo "Despliegue completado correctamente."
