trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals ip-172-31-8-73

variables:
  deployPath: '/var/www/contratos'
  serverIP: '172.31.8.73'
  sshUser: 'ec2-user'
  sshKey: '$(SSH_PRIVATE_KEY)'

stages:
- stage: Deploy
  displayName: 'Deploy to AWS Linux Server'
  jobs:
  - job: Deploy
    displayName: 'Copy File and Restart Service'
    steps:
    - checkout: self
      displayName: 'Checkout Code'

    - script: |
        echo "Listando archivos del agente:"
        ls -la /home/ec2-user/myagent/_work
      displayName: 'Listar Archivos del Agente'

    - task: Bash@3
      displayName: 'Copy and Restart Service'
      inputs:
        targetType: 'inline'
        script: |
          echo "Iniciando despliegue..."

          # Crear clave privada temporal
          echo "$(sshKey)" > private_key.pem
          chmod 600 private_key.pem

          # Crear carpeta destino
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) "sudo mkdir -p $(deployPath) && sudo chown ec2-user:ec2-user $(deployPath)"

          # Copiar archivo al servidor
          scp -o StrictHostKeyChecking=no -i private_key.pem /home/ec2-user/myagent/_work/1/a/drop/Zubeldia.zip $(sshUser)@$(serverIP):$(deployPath)/Zubeldia.zip

          # Verificar archivos copiados
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) "ls -la $(deployPath)"

          # Descomprimir archivo y reiniciar servicio
          ssh -o StrictHostKeyChecking=no -i private_key.pem $(sshUser)@$(serverIP) << 'EOF'
          unzip -o $(deployPath)/Zubeldia.zip -d $(deployPath)
          sudo systemctl daemon-reload
          sudo systemctl restart contratos.service
          EOF

          rm -f private_key.pem
          echo "Despliegue completado correctamente."
